// <auto-generated />
namespace OnlineEventManagement.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class category1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003301032483_category1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
