// <auto-generated />
namespace OnlineEventManagement.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class uniquekey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uniquekey));
        
        string IMigrationMetadata.Id
        {
            get { return "202003030439090_uniquekey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
